project:
  type: website
  output-dir: ../_site/en

website:
  title: "Benjamin Peeters"
  site-url: "https://benjaminpeeters.github.io/en"

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Data & Code"
        href: data-code.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: translate
        menu:
          - text: "English"
            href: /en/index.html
          - text: "Français"
            href: /fr/index.html
          - text: "中文"
            href: /zh/index.html
      - icon: github
        href: https://github.com/benjaminpeeters
        aria-label: GitHub

format:
  html:
    theme:
      light: [cosmo, ../custom.scss]
      dark: [darkly, ../custom-dark.scss]
    css: ../styles.css
    include-in-header:
      - ../state-manager.html
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
    include-after-body: ../footer-en.html
    toc: true
    lang: en

bibliography: ../publications.bib
