# Navigation Links - Chinese

main:
  - name: 主页
    url: /
    weight: 10
  - name: 出版物
    url: /publications/
    weight: 20
  - name: 数据与代码
    url: /data-code/
    weight: 30
  - name: 教学
    url: /teaching/
    weight: 40
  - name: 关于
    url: /about/
    weight: 50
  - name: 联系
    url: /contact/
    weight: 60
